### PR TITLE
bring back pie chart in listings page

### LINKED ISSUE #116: The graph in /listings is causing issues
The pie graph, once loaded, is taking up all of the space. Probably needs to be remove.

### PR DESCRIPTION
**Pull request by shackbarth**
resolves #116 

This isn't the most modern code but I imagine we don't need to install a bunch of javascript tooling on the app right now.

### CODE REVIEW

**Comment by shackbarth** [comment]
Also if it's ok I'd like to swap out d3plus for highcharts, which will look nicer. But that can be a different PR.

**Comment by mzagaja** [comment]
Thanks @shackbarth I tested it and it works great. Fix seems simple enough so no real suggestions on refactoring or anything. @AlexMerritt is it ok if I merge this in?

**Comment by shackbarth** [comment]
stats-page

**Comment by shackbarth** [comment]
That's what it looks like now

**Comment by shackbarth** [comment]
resolves #117

**Pull request merged**
